"""names.toml: readable names for obfuscated identifiers.

The unit is the IDENTIFIER, not the column: the obfuscator maps one original
identifier to one name per build, so naming `NOHLEFCNDPA` once names it in
every table and struct that uses it.

Obfuscated names change every build, so each entry carries an ANCHOR — the
identifier's declaration position from a table's row type ("Warp_Data/4/2":
row field #4, then its field #2). Table names are plaintext literals and
declaration order is kept across builds, so `suggest` re-resolves every anchor
against the current rom_dump.cs and re-keys entries whose identifier changed.

Entries have a status: "confirmed" ones are the curated truth and are never
changed by the tool (except re-keying); "suggested" ones are regenerated by
every `suggest` run from the evidence (UI traces, row keys). Confirm a
suggestion by editing its name if needed and setting status = "confirmed".
"""

from __future__ import annotations

import collections
import json
import re
import tomllib
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path

from .dump import Dump, elem_type

MAX_DEPTH = 8
MIN_PRECISION = 0.6  # UI number evidence below this is a coincidence
COMMON_KEY_TABLES = 10  # a row key shared by this many tables is the generic "index"
EVIDENCE_LINES = 5
HEADER = """\
# Readable names for obfuscated identifiers — see datatables/names.py.
# `python -m datatables suggest` re-keys entries to the current build (via
# `anchor`) and regenerates the "suggested" ones from the evidence; entries
# with status = "confirmed" are never changed. To accept a suggestion, fix its
# name if needed and set status = "confirmed".
"""
LABEL_PREFIXES = ("Text_", "Txt_", "Lbl_", "Label_", "TMP_", "UIText_")
GENERIC_LEAVES = {"", "Text", "UIText", "Label", "Value", "TMP"}


@dataclass
class Entry:
    name: str
    status: str = "suggested"
    anchor: str = ""
    score: float = 0.0
    evidence: list[str] = field(default_factory=list)


# ---------------------------------------------------------------- file

def load(path: Path) -> dict[str, Entry]:
    if not path.is_file():
        return {}
    with path.open("rb") as handle:
        raw = tomllib.load(handle)
    return {k: Entry(v["name"], v.get("status", "suggested"), v.get("anchor", ""), v.get("score", 0.0),
                     list(v.get("evidence", []))) for k, v in raw.items()}


def save(path: Path, entries: dict[str, Entry]) -> None:
    def q(s: str) -> str:
        return json.dumps(s, ensure_ascii=False)  # JSON escapes are valid TOML basic strings

    confirmed = sorted((k for k, e in entries.items() if e.status == "confirmed"), key=lambda k: entries[k].name)
    suggested = sorted((k for k, e in entries.items() if e.status != "confirmed"), key=lambda k: -entries[k].score)
    lines = [HEADER]
    for title, keys in (("confirmed", confirmed), ("suggested", suggested)):
        if keys:
            lines.append(f"# ---- {title} ({len(keys)}) " + "-" * 50 + "\n")
        for k in keys:
            e = entries[k]
            lines.append(f"[{k}]")
            lines.append(f"name = {q(e.name)}")
            lines.append(f"status = {q(e.status)}")
            if e.anchor:
                lines.append(f"anchor = {q(e.anchor)}")
            if e.status != "confirmed":
                lines.append(f"score = {e.score:.1f}")
            if e.evidence:
                lines.append("evidence = [")
                lines.extend(f"  {q(line)}," for line in e.evidence)
                lines.append("]")
            lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def confirmed_names(entries: dict[str, Entry], include_suggested: bool = False) -> dict[str, str]:
    return {k: e.name for k, e in entries.items() if e.status == "confirmed" or include_suggested}


# ---------------------------------------------------------------- anchors

def anchors(dump: Dump) -> dict[str, str]:
    """identifier -> anchor 'Table/i/j/...': its shortest declaration path from
    a table's row type. Breadth-first, each type expanded once — following
    the declared type graph path by path explodes combinatorially."""
    out: dict[str, str] = {}
    expanded: set[str] = set()
    queue = deque((dump.row_type(t), t, []) for t in sorted(dump.tables) if dump.row_type(t) in dump.types)
    while queue:
        t, table, pos = queue.popleft()
        if t in expanded:
            continue
        expanded.add(t)
        for i, (ft, name, _) in enumerate(dump.types.get(t, [])):
            path = pos + [i]
            out.setdefault(name, "/".join([table, *map(str, path)]))
            inner = elem_type(ft) or ft
            if inner in dump.types and inner not in expanded and len(path) < MAX_DEPTH:
                queue.append((inner, table, path))
    return out


def resolve(dump: Dump, anchor: str) -> str | None:
    table, *pos = anchor.split("/")
    t, name = dump.row_type(table), None
    for i in map(int, pos):
        fields = dump.types.get(t)
        if not fields or i >= len(fields):
            return None
        ft, name, _ = fields[i]
        t = elem_type(ft) or ft
    return name


def migrate(dump: Dump, entries: dict[str, Entry]) -> tuple[dict[str, Entry], list, list]:
    """Re-key entries to the identifiers their anchors resolve to in this build.
    -> (entries, [(old, new)], [stale keys whose anchor no longer resolves])."""
    out, moved, stale = {}, [], []
    for key, e in sorted(entries.items(), key=lambda kv: kv[1].status != "confirmed"):
        new = resolve(dump, e.anchor) if e.anchor else key
        if new is None:
            stale.append(key)
            new = key
        elif new != key:
            moved.append((key, new))
        if new not in out:  # confirmed entries were placed first and win
            out[new] = e
    return out, moved, stale


# ---------------------------------------------------------------- suggestions

def identifier(path: str) -> str:
    """Column path -> the identifier it ends in ('A.B[].C' -> 'C', 'A[]' -> 'A')."""
    return path.rsplit(".", 1)[-1].removesuffix("[]")


def camel(words: list[str]) -> str:
    words = [w for w in words if w]
    if not words:
        return ""
    return words[0][:1].lower() + words[0][1:] + "".join(w[:1].upper() + w[1:] for w in words[1:])


def draft_name(label: str, position: int | None = None, count: int = 1, ranged: bool = False) -> str:
    """A starting point from the UI label: 'Btn_Field/Text_WorldLevel', first of
    'Lv 95~97' -> 'worldLevelMin'. Meant to be edited when confirming."""
    parent, _, leaf = label.rpartition("/")
    for part in (leaf, parent):
        core = part
        for prefix in LABEL_PREFIXES:
            if core.startswith(prefix):
                core = core[len(prefix):]
                break
        if core not in GENERIC_LEAVES:
            break
    name = camel(re.split(r"[_\s]+", core))
    if count > 1 and position is not None:
        name += ("Min", "Max")[position] if ranged and count == 2 and position < 2 else str(position + 1)
    return name


def id_columns(tables: dict[str, dict]) -> dict[str, list[str]]:
    """identifier -> tables where it is the row key (top-level field == key in every row)."""
    out = collections.defaultdict(list)
    for table, rows in sorted(tables.items()):
        if not rows:
            continue
        first = next(iter(rows.values()))
        for f in first:
            if all(isinstance(r, dict) and r.get(f) == k for k, r in rows.items()):
                out[f].append(table)
                break
    return out


def candidates(evidence: dict, ids: dict[str, list[str]]) -> dict[str, list[tuple[float, str, str]]]:
    """identifier -> [(weight, draft name, evidence line)] from every source."""
    out = collections.defaultdict(list)
    for ident, tables in ids.items():
        # The common row key (SystemLocalization and the protocol call it Index).
        # A table keyed by another identifier had another original name there.
        if len(tables) >= COMMON_KEY_TABLES:
            out[ident].append((1000.0 + len(tables), "index", f"row key in {len(tables)} tables"))
        else:
            draft = camel(re.split(r"_|(?<=[a-z])(?=[A-Z])", tables[0])) + "Index"
            out[ident].append((100.0 + len(tables), draft, f"row key of {', '.join(tables)}"))
    for c in evidence.get("columns", []):
        ident, col = identifier(c["path"]), f"{c['table']}.{c['path']}"
        captions = f" [{', '.join(c['captions'])}]" if c.get("captions") else ""
        if c["kind"] == "number":
            if c["precision"] < MIN_PRECISION:
                continue
            draft = draft_name(c["label"], c["position"], c["numbers"], c["range"])
            line = (f"ui: {col} <- {c['label']}{captions}, {c['records']} records, "
                    f"{c['precision']:.0%} precise, e.g. {c['examples'][0]}")
            out[ident].append((c["records"] * c["precision"], draft, line))
        elif c["kind"] == "anchor":
            labels = ", ".join(lab for lab, _ in c["labels"][:3])
            out[ident].append((float(c["records"]), draft_name(c["label"]),
                               f"ui text: {col} shown in {labels} ({c['records']} records)"))
        elif c["kind"] == "valueset":
            out[ident].append((c["values"] * 0.5, draft_name(c["label"]),
                               f"ui values: {col} holds all {c['values']} values of {c['label']}{captions} "
                               f"({c['distinct']} distinct in column)"))
    return out


def suggest(dump: Dump, entries: dict[str, Entry], evidence: dict, tables: dict[str, dict]):
    """-> (entries, stats). Confirmed entries are kept; suggested ones rebuilt."""
    entries, moved, stale = migrate(dump, entries)
    entries = {k: e for k, e in entries.items() if e.status == "confirmed"}
    where = anchors(dump)
    added = 0
    for ident, cands in candidates(evidence, id_columns(tables)).items():
        if ident in entries:
            continue
        cands.sort(key=lambda c: -c[0])
        weight, draft, _ = cands[0]
        if not draft:
            continue
        lines = [f"{d} <- {line}" for _, d, line in cands[:EVIDENCE_LINES]]
        others = sorted({d for w, d, _ in cands[1:] if d != draft and w >= weight / 2})
        if others:
            lines.insert(0, f"conflict: evidence also suggests {', '.join(others)}")
        entries[ident] = Entry(draft, "suggested", where.get(ident, ""), round(weight, 1), lines)
        added += 1
    return entries, {"moved": moved, "stale": stale, "suggested": added,
                     "confirmed": sum(e.status == "confirmed" for e in entries.values())}


# ---------------------------------------------------------------- applying

def rename(value, names: dict[str, str]):
    """Rename obfuscated keys everywhere in a decoded row. A name that would
    collide with a sibling key keeps the obfuscated one."""
    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            n = names.get(k, k)
            if n in out or (n != k and n in value):
                n = k
            out[n] = rename(v, names)
        return out
    if isinstance(value, list):
        return [rename(v, names) for v in value]
    return value
