"""names.toml: readable names for obfuscated identifiers.

The unit is the IDENTIFIER, not the column: the obfuscator maps one original
identifier to one name per build, so naming `NOHLEFCNDPA` once names it in
every table and struct that uses it.

Obfuscated names change every build, so each entry carries an ANCHOR — the
identifier's declaration position from a table's row type ("Warp_Data/4/2":
row field #4, then its field #2). Table names are plaintext literals and
declaration order is kept across builds, so `suggest` re-resolves every anchor
against the current rom_dump.cs and re-keys entries whose identifier changed.

Entries have a status: "confirmed" ones are the curated truth and are never
changed by the tool (except re-keying); "tentative" ones are hand-written
guesses (from data patterns, not proof), kept like confirmed ones but applied
only with `names = "all"`; "suggested" ones are regenerated by every `suggest`
run from the evidence (UI traces, row keys, code). Confirm a suggestion by
editing its name if needed and setting status = "confirmed".
"""

from __future__ import annotations

import collections
import json
import re
import tomllib
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path

from .code import obfuscated
from .dump import Dump, elem_type

MAX_DEPTH = 8
MIN_PRECISION = 0.6  # UI number evidence below this is a coincidence
COMMON_KEY_TABLES = 10  # a row key shared by this many tables is the generic "index"
EVIDENCE_LINES = 5
HEADER = """\
# Readable names for obfuscated identifiers — see datatables/names.py.
# `python -m datatables suggest` re-keys entries to the current build (via
# `anchor`) and regenerates the "suggested" ones from the evidence; entries
# with status = "confirmed" or "tentative" (a hand-written guess, applied only
# with names = "all") are never changed. To accept a suggestion, fix its name
# if needed and set status = "confirmed".
"""
CURATED = ("confirmed", "tentative")  # written by hand: `suggest` keeps them
LABEL_PREFIXES = ("Text_", "Txt_", "Lbl_", "Label_", "TMP_", "UIText_")
GENERIC_LEAVES = {"", "Text", "UIText", "Label", "Value", "TMP"}
# Drafts that say nothing about a column (`Text_2`, `Text_Off`, `Mask/Text_Info`):
# a number column falls back to "value", other evidence is dropped.
GENERIC_DRAFTS = {"number", "info", "on", "off", "after", "before", "menu", "drop", "type", "text", "count",
                  "countText", "desc", "sub", "main", "content", "slot", "icon", "btn", "button", "tab"}
STATE_WEIGHT = 5  # a game field name outweighs a UI label: it is the programmer's name for the value
HUNGARIAN_RE = re.compile(r"^(?:v|n|s|f|b|bl|str|txt|text|list|arr|dic|dict|e|i|l|u|ul|d|go|tr|img|tm|tmp)(?=[A-Z])")
MIN_ANCHOR_RECORDS = 10  # a string column needs this many records to be named after its label
MIN_ANCHOR_SHARE = 0.5  # ... and its top label must hold this share of them (not a coincidence across screens)
GETTER_WEIGHT = 40.0  # a plaintext getter returning the field names it as its programmer did
CODE_CONTEXT_LINES = 2  # "read in <plaintext method>" lines added to an entry's evidence


@dataclass
class Entry:
    name: str
    status: str = "suggested"
    anchor: str = ""
    score: float = 0.0
    evidence: list[str] = field(default_factory=list)


# ---------------------------------------------------------------- file

def load(path: Path) -> dict[str, Entry]:
    if not path.is_file():
        return {}
    with path.open("rb") as handle:
        raw = tomllib.load(handle)
    return {k: Entry(v["name"], v.get("status", "suggested"), v.get("anchor", ""), v.get("score", 0.0),
                     list(v.get("evidence", []))) for k, v in raw.items()}


def save(path: Path, entries: dict[str, Entry]) -> None:
    def q(s: str) -> str:
        return json.dumps(s, ensure_ascii=False)  # JSON escapes are valid TOML basic strings

    sections = [(status, sorted((k for k, e in entries.items() if e.status == status), key=lambda k: entries[k].name))
                for status in CURATED]
    sections.append(("suggested", sorted((k for k, e in entries.items() if e.status not in CURATED),
                                         key=lambda k: -entries[k].score)))
    lines = [HEADER]
    for title, keys in sections:
        if keys:
            lines.append(f"# ---- {title} ({len(keys)}) " + "-" * 50 + "\n")
        for k in keys:
            e = entries[k]
            lines.append(f"[{k}]")
            lines.append(f"name = {q(e.name)}")
            lines.append(f"status = {q(e.status)}")
            if e.anchor:
                lines.append(f"anchor = {q(e.anchor)}")
            if e.status not in CURATED:
                lines.append(f"score = {e.score:.1f}")
            if e.evidence:
                lines.append("evidence = [")
                lines.extend(f"  {q(line)}," for line in e.evidence)
                lines.append("]")
            lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def confirmed_names(entries: dict[str, Entry], include_suggested: bool = False) -> dict[str, str]:
    return {k: e.name for k, e in entries.items() if e.status == "confirmed" or include_suggested}


# ---------------------------------------------------------------- anchors

def anchors(dump: Dump) -> dict[str, str]:
    """identifier -> anchor 'Table/i/j/...': its shortest declaration path from
    a table's row type. Breadth-first, each type expanded once — following
    the declared type graph path by path explodes combinatorially."""
    out: dict[str, str] = {}
    expanded: set[str] = set()
    queue = deque((dump.row_type(t), t, []) for t in sorted(dump.tables) if dump.row_type(t) in dump.types)
    while queue:
        t, table, pos = queue.popleft()
        if t in expanded:
            continue
        expanded.add(t)
        for i, (ft, name, _) in enumerate(dump.types.get(t, [])):
            path = pos + [i]
            out.setdefault(name, "/".join([table, *map(str, path)]))
            inner = elem_type(ft) or ft
            if inner in dump.types and inner not in expanded and len(path) < MAX_DEPTH:
                queue.append((inner, table, path))
    return out


def resolve(dump: Dump, anchor: str) -> str | None:
    table, *pos = anchor.split("/")
    t, name = dump.row_type(table), None
    for i in map(int, pos):
        fields = dump.types.get(t)
        if not fields or i >= len(fields):
            return None
        ft, name, _ = fields[i]
        t = elem_type(ft) or ft
    return name


def migrate(dump: Dump, entries: dict[str, Entry]) -> tuple[dict[str, Entry], list, list]:
    """Re-key entries to the identifiers their anchors resolve to in this build.
    -> (entries, [(old, new)], [stale keys whose anchor no longer resolves])."""
    out, moved, stale = {}, [], []
    for key, e in sorted(entries.items(), key=lambda kv: kv[1].status not in CURATED):
        new = resolve(dump, e.anchor) if e.anchor else key
        if new is None:
            stale.append(key)
            new = key
        elif new != key:
            moved.append((key, new))
        if new not in out:  # curated entries were placed first and win
            out[new] = e
    return out, moved, stale


# ---------------------------------------------------------------- suggestions

def identifier(path: str) -> str:
    """Column path -> the identifier it ends in ('A.B[].C' -> 'C', 'A[]' -> 'A')."""
    return path.rsplit(".", 1)[-1].removesuffix("[]")


def camel(words: list[str]) -> str:
    words = [w for w in words if w]
    if not words:
        return ""
    return words[0][:1].lower() + words[0][1:] + "".join(w[:1].upper() + w[1:] for w in words[1:])


def generic(draft: str) -> bool:
    return not draft or not draft[0].isalpha() or draft in GENERIC_DRAFTS


def draft_name(label: str, position: int | None = None, count: int = 1, ranged: bool = False,
               fallback: str = "") -> str:
    """A starting point from the UI label: 'Btn_Field/Text_WorldLevel', first of
    'Lv 95~97' -> 'worldLevelMin'. A label that names nothing ('Text_2') gives
    `fallback` ('' = no draft). Meant to be edited when confirming."""
    parent, _, leaf = label.rpartition("/")
    for part in (leaf, parent):
        core = part
        for prefix in LABEL_PREFIXES:
            if core.startswith(prefix):
                core = core[len(prefix):]
                break
        if core not in GENERIC_LEAVES:
            break
    name = camel(re.split(r"[_\s]+", core))
    if generic(name):
        name = fallback
        if not name:
            return ""
    if count > 1 and position is not None:
        name += ("Min", "Max")[position] if ranged and count == 2 and position < 2 else str(position + 1)
    return name


def code_name(field: str) -> str:
    """A game field name -> a draft: 'm_vMapSize' -> 'mapSize', 'm_nMapID' ->
    'mapID', 'm_X' -> 'x', '_nWarpIndex' -> 'warpIndex', 'm_txtTitle' -> 'title'."""
    if field.endswith("__"):  # compiler-made (value__)
        return ""
    name = field
    for prefix in ("m_", "_"):
        if name.startswith(prefix):
            name = name[len(prefix):]
            break
    name = HUNGARIAN_RE.sub("", name)
    name = name[:1].lower() + name[1:]
    return "" if generic(name) else name


def id_columns(tables: dict[str, dict]) -> dict[str, list[str]]:
    """identifier -> tables where it is the row key (top-level field == key in every row)."""
    out = collections.defaultdict(list)
    for table, rows in sorted(tables.items()):
        if not rows:
            continue
        first = next(iter(rows.values()))
        for f in first:
            if all(isinstance(r, dict) and r.get(f) == k for k, r in rows.items()):
                out[f].append(table)
                break
    return out


def candidates(evidence: dict, ids: dict[str, list[str]]) -> dict[str, list[tuple[float, str, str]]]:
    """identifier -> [(weight, draft name, evidence line)] from every source."""
    out = collections.defaultdict(list)
    for ident, tables in ids.items():
        # The common row key (SystemLocalization and the protocol call it Index).
        # A table keyed by another identifier had another original name there.
        if len(tables) >= COMMON_KEY_TABLES:
            out[ident].append((1000.0 + len(tables), "index", f"row key in {len(tables)} tables"))
        else:
            draft = camel(re.split(r"_|(?<=[a-z])(?=[A-Z])", tables[0])) + "Index"
            out[ident].append((100.0 + len(tables), draft, f"row key of {', '.join(tables)}"))
    for c in evidence.get("columns", []):
        ident, col = identifier(c["path"]), f"{c['table']}.{c['path']}"
        captions = f" [{', '.join(c['captions'])}]" if c.get("captions") else ""
        if c["kind"] == "number":
            if c["precision"] < MIN_PRECISION:
                continue
            draft = draft_name(c["label"], c["position"], c["numbers"], c["range"], fallback="value")
            scale = f", shown / {c['scale']}" if c.get("scale", 1) != 1 else ""
            line = (f"ui: {col} <- {c['label']}{captions}, {c['records']} records, "
                    f"{c['precision']:.0%} precise{scale}, e.g. {c['examples'][0]}")
            out[ident].append((c["records"] * c["precision"], draft, line))
        elif c["kind"] == "anchor":
            share = c["labels"][0][1] / sum(n for _, n in c["labels"])
            if c["records"] < MIN_ANCHOR_RECORDS or share < MIN_ANCHOR_SHARE or not (draft := draft_name(c["label"])):
                continue
            labels = ", ".join(lab for lab, _ in c["labels"][:3])
            out[ident].append((float(c["records"]), draft,
                               f"ui text: {col} shown in {labels} ({c['records']} records)"))
        elif c["kind"] == "state":
            if c["precision"] < MIN_PRECISION:
                continue
            fields = c["label"].split(".")[1:]  # "CMapManager.m_vMapSize.m_X" -> m_vMapSize, m_X
            weight = STATE_WEIGHT * c["records"] * c["precision"]
            scale = f", shown / {c['scale']}" if c.get("scale", 1) != 1 else ""
            line = (f"state: {col} == {c['label']}, {c['records']} snapshots ({c['values']} values), "
                    f"{c['precision']:.0%} precise{scale}, e.g. {c['examples'][0]}")
            if draft := code_name(fields[-1]):
                out[ident].append((weight, draft, line))
            # the struct around it: MFGNLFAOAGB.BPFBMIDLJKI == m_vMapSize.m_X -> MFGNLFAOAGB is mapSize
            if len(fields) > 1 and "." in c["path"] and (parent := code_name(fields[-2])):
                out[identifier(c["path"].rsplit(".", 1)[0])].append((weight / 2, parent, line))
        elif c["kind"] == "valueset":
            if not (draft := draft_name(c["label"])):
                continue
            out[ident].append((c["values"] * 0.5, draft,
                               f"ui values: {col} holds all {c['values']} values of {c['label']}{captions} "
                               f"({c['distinct']} distinct in column)"))
    return out


def suggest(dump: Dump, entries: dict[str, Entry], evidence: dict, tables: dict[str, dict], code: dict | None = None):
    """-> (entries, stats). Curated entries are kept; suggested ones rebuilt.
    `code` is xref.json: drafts from getters/setters, context lines for curating."""
    entries, moved, stale = migrate(dump, entries)
    entries = {k: e for k, e in entries.items() if e.status in CURATED}
    where = anchors(dump)
    added = 0
    all_cands = candidates(evidence, id_columns(tables))
    for ident, cands in code_candidates(code or {}).items():
        all_cands.setdefault(ident, []).extend(cands)
    context = code_context(code or {})
    for ident, cands in all_cands.items():
        if ident in entries:
            continue
        cands.sort(key=lambda c: -c[0])
        weight, draft, _ = cands[0]
        if not draft:
            continue
        lines = [f"{d} <- {line}" for _, d, line in cands[:EVIDENCE_LINES]]
        others = sorted({d for w, d, _ in cands[1:] if d != draft and w >= weight / 2})
        if others:
            lines.insert(0, f"conflict: evidence also suggests {', '.join(others)}")
        lines += [line for line in context.get(ident, []) if len(lines) < EVIDENCE_LINES + CODE_CONTEXT_LINES]
        entries[ident] = Entry(draft, "suggested", where.get(ident, ""), round(weight, 1), lines)
        added += 1
    return entries, {"moved": moved, "stale": stale, "suggested": added,
                     "confirmed": sum(e.status == "confirmed" for e in entries.values()),
                     "tentative": sum(e.status == "tentative" for e in entries.values())}


# ---------------------------------------------------------------- code evidence (xref.json)

def code_candidates(code: dict) -> dict[str, list[tuple[float, str, str]]]:
    """identifier -> [(weight, draft, line)]: a plaintext method whose whole body
    returns the field names it (`get_IsNotPet` -> isNotPet)."""
    out = collections.defaultdict(list)
    for owner, fields in code.get("fields", {}).items():
        for fname, info in fields.items():
            for r in info["top"]:
                if r.get("getter"):
                    out[fname].append((GETTER_WEIGHT, r["getter"], f"code: {owner}.{fname} is returned by {r['m']}"))
    return out


def code_context(code: dict) -> dict[str, list[str]]:
    """identifier -> lines pointing at plaintext readers, for curating
    (`datatables xref TABLE.COLUMN` has more). A Set<Name>(value) the field goes
    straight into comes first, but only as context: the setter's name says what
    the callee does with the value (SetData(int)), not always what it is."""
    out = collections.defaultdict(list)
    for owner, fields in code.get("fields", {}).items():
        for fname, info in fields.items():
            readers = sorted(info["top"], key=lambda r: not r.get("setter"))
            for r in readers:
                if len(out[fname]) >= CODE_CONTEXT_LINES:
                    break
                meth = r["m"].rpartition("::")[2]
                if r.get("getter") or (obfuscated(meth) and not r.get("setter")):
                    continue
                if r.get("setter"):
                    out[fname].append(f"code: {owner}.{fname} is passed to {r['setter']} in {r['m']}")
                    continue
                strings = f", strings {r['s'][:3]}" if r["s"] else ""
                calls = f" -> {', '.join(r['c'][:3])}" if r["c"] else ""
                out[fname].append(f"code: {owner}.{fname} read in {r['m']}{strings}{calls}")
    return out


# ---------------------------------------------------------------- applying

def rename(value, names: dict[str, str]):
    """Rename obfuscated keys everywhere in a decoded row. A name that would
    collide with a sibling key keeps the obfuscated one."""
    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            n = names.get(k, k)
            if n in out or (n != k and n in value):
                n = k
            out[n] = rename(v, names)
        return out
    if isinstance(value, list):
        return [rename(v, names) for v in value]
    return value
